/*

Here is the API you gave to the players

With that API, they can connect to the server, play move, display the game, send comments, etc.

*/


#ifndef __API_CLIENT_TEMPLATE__
#define __API_CLIENT_TEMPLATE__
#include "ret_type.h"
#define MAX_TOKEN_AMOUNT 10


/* define here the type defining a move */

/* A move is defined by ...*/
typedef enum
{
    REDISTRIBUTE    = "re",
    TAKE_A_TOKEN    = "1to",
    TAKE_TOKENS     = "to",
    BOOK_CARD       = "book_card",
    BOOK_BLIND_CARD = "book_blind",
    BUY_JCARD       = "buy_card",
    BUY_BOOKED      = "buy_booked",
    ROYAL_CARD      = "royal"

} t_move;


typedef enum {
    NONE = 0,
    PEARL = 1,
    GOLD = 2,
    BLUE_SAPPHIRE = 3,
    DIAMOND = 4,
    EMERALD = 5,
    RUBY = 6,
    OBSIDIAN = 7,
} t_color;

typedef enum {
    NO_ABILITY = 0,
    PLAY_AGAIN = 1,
    CHOOSE_GEMSTONE = 2,
    TAKE_A_TOKEN = 3,
    GET_A_PRIVILEGE_SCROLL = 4,
    STEAL_GEMSTONE_PEARL = 5
} t_ability;

typedef enum {
    TOKEN_TYPE,
    NB_JEWELS,
    NB_PRESTIGE_POINTS,
    NB_CROWNS,
    ABILITY1,
    ABILITY2,
    REQ_PEARL,
    REQ_SAPPHIRE,
    REQ_DIAMOND,
    REQ_EMERALD,
    REQ_RUBY,
    REQ_OBSIDIAN
} jewel_card;


/* -------------------------------------
 * Initialize connection with the server
 * Quit the program if the connection to the server
 * cannot be established
 *
 * Parameters:
 * - serverName: (string) address of the server
 *   (it could be "localhost" if the server is run in local,
 *   or "pc4521.polytech.upmc.fr" if the server runs there)
 * - port: (int) port number used for the connection
 * - name: (string) name of the bot : max 20 characters
 *         (checked by the server)
 */
void connectToServer( char* serverName, int port, char* name);



/* ----------------------------------
 * Close the connection to the server
 * to do, because we are polite
 *
 * Parameters:
 * None
*/
void closeConnection();


/* ----------------------------------------------------------------
 * Wait for a Game, and retrieve its name and first data
 * (typically, array sizes)
 *
 * Parameters:
 * - gameType: string (max 50 characters)
 * - gameName: string (max 50 characters),
 *              corresponds to the game name (a unique ID automatically generated by the server)
 * - insert your size data here...
 *
 * gameType is a string like "NAME key1=value1 key2=value1 ..."
 * - NAME can be empty. It gives the type of the training player
 * - key=value pairs are used for options
 *   (each training player has its own options)
 *   invalid keys are ignored, invalid values leads to error
 *   the following options are common to every training player
 *   (when NAME is not empty or not TOURNAMENT):
 *        - 'timeout': allows an define the timeout
 *                   when training (in seconds)
 *        - 'seed': allows to set the seed of the random generator
 *        - 'start': allows to set who starts ('0' or '1')
 * gameType could also be : "TOURNAMENT name" where name is the name of the tournament
  */
void waitForSplendorGame( char* gameType, char* gameName);

/* -------------------------------------
 * Get the data and tell who starts
 *
 * Parameters:
 * - data: pointer to data to fill
 *   (the pointer data MUST BE allocated with the right size!! (see below))
 *
 * Returns 0 if you begin, or 1 if the opponent begins
 * 
 * Data that will fill the pointer:
 *  25 digits (0,1,...,9) representing the board;
 *  5*12 digits (5 level-1 Jewel Cards); ┐
 *  4*12 digits (4 level-2 JCards);      │-> This is the data from the pyramid (see printSplendorGame for a better visual understanding)
 *  3*12 digits (3 level-3 JCards);      ┘
 *  4*2 digits (4 royal cards)
 * (Don't forget the spaces for separation between the digits!)
 */
int getSplendorGameData(char* data);


/* ----------------------
 * Get the opponent move
 *
 * Parameters:
 * - move: a move
 *
 * Returns a return_code
 * NORMAL_MOVE for normal move,
 * WINNING_MOVE for a winning move, -1
 * LOOSING_MOVE for a losing (or illegal) move
 * this code is relative to the opponent (WINNING_MOVE if HE wins, ...)
 * 
 * 
 */
t_return_code getMove(t_move* move, int* data);
//on a besoin de savoir quel move a été fait
  //quelles sont les données associées au move 
  //si l'adversaire a fait un optionaltakeatoekn(), il faut savoir que c'étati un optionaltakeatoken , et quelles coordonnées
  //si c'était un redistribute, il faut aussi savoir quel est l'état de la board
  //taketokens: coordonnées, et lesquelles rendures
  //bookcard: level et index
  //bookblindcard: rien à part que ceest ce move
  //

//quand on fait un getmove, on récupère un entier qui est le type du move (faire des DEFINE pour les coups possibles)
// getmove(int move, int* data) // qui est un tableau de 25 entiers
// commenter à chaque fois la data et le smoves




/* -----------
 * Send a move
 *
 * Parameters:
 * - move: a move
 *
 * Returns a return_code
 * NORMAL_MOVE for normal move,
 * WINNING_MOVE for a winning move, -1
 * LOOSING_MOVE for a losing (or illegal) move
 * this code is relative to your programm (WINNING_MOVE if YOU win, ...)
 */
t_return_code sendMove( t_move move );
//outdated considering we made multiple functions depending on the move(s) we're choosing?


/* -----------
 * Play optional move: take a token. 
 * You're choosing a token on the board at the cost of a privilege scroll (to give to your opponent)
 * (and you might return a token, assuming you have 10).
 * 
 * Parameters are the following:
 *    - x: Row (frop top to bottom) on the board (0-indexed)
 *    - y: Column (from left to right) on the board (also 0-indexed)
 *    - returnedToken: Color of the token you'll return, assuming you already have 10 (-1 if irrelevant)
 *                      (which means you're trading the token you're capturing for the returnedToken)
 *                      (which goes without saying you need to own the token you're returning, otherwise
 *                      this move would be considered illegal. As a result, you'd loose the game)
 * .
 * Returns a t_return_code:
 *    - NORMAL_MOVE for legal move,
 *    - WINNING_MOVE for a winning move,
 *    - LOOSING_MOVE for a losing (or illegal) move
 *      (e.g. not returning any token while having 10).
 * This code is relative to your program (WINNING_MOVE if YOU win, ...)
 */
t_return_code optionalTakeAToken(int x, int y, int returnedToken);


/* -----------
 * Redistribute your tokens in case there's none on the board anymore.
 * This move fills the board with the tokens in the bank (i.e. in nobody's inventory)
 *
 * Parameters:
 *    - newBoard: A pointer to an array of 25 integers representing the board's state
 *                after redistribution (tokens, cards, prestige, etc.).
 *                This array replaces your previous state entirely.
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the redistribution is valid (it should always be the case),
 *    - WINNING_MOVE if this move results in a victory (which should never happen),
 *    - LOOSING_MOVE if the move is invalid (which should never happen).
 */
t_return_code redistribute(int* newBoard);


/* -----------
 * One of the mandatory moves: take tokens on the board.
 * Pick up to 3 different tokens from the board.
 * You specify the 3 token positions (x,y) you wish to take, along with
 * the 3 token colors you want to return (if necessary).
 *
 * /!\ You can only return tokens if you exceed the 10-token limit **after** taking the new ones.
 * If you don't exceed the limit, set c1, c2, c3 to -1.
 * It goes the same as the optional take a token move:
 * you are responsible for ensuring that you actually own the tokens you're returning (otherwise you lose).
 *
 * Parameters:
 *    - (x1, y1), (x2, y2), (x3, y3): positions on the board (0-indexed rows and columns)
 *      of the 3 tokens you want to take. (use -1 on (x3, y3) if you're not taking a third
 *      and use -1 on (x2, y2) and (x3, y3) if you're only capturing one token).
 *    - c1, c2, c3: colors of the tokens you're returning (use -1 if not applicable).
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the move is valid,
 *    - WINNING_MOVE if the move results in a win,
 *    - LOOSING_MOVE if the move is illegal (e.g. returning tokens you don't own, not returning enough tokens).
 */
t_return_code takeTokens(int x1, int y1, int x2, int y2, int x3, int y3, int c1, int c2, int c3); //c1,c2,c3: tokens to return if you go above the threshold of 10 tokens


/* -----------
 * Reserve a visible card from the board ("book" it).
 * This move lets you select a card from a visible row of the pyramid (level 1, 2 or 3)
 * and add it to your reserved cards. (see printSplendorGame() for better visual understanding).
 * 
 * Maximum amount of booked cards at the same time: 3.
 * ⚠️⚠️
 *  TODO 
 *   This move automatically grants you a gold token, unless you're already at the max token capacity (10).
 * 
 * You may later buy this card using `buyBookedCard()` (see below).
 *
 * Parameters:
 *    - level: the card level 
 *             (1 = level-1 card (top row), 
 *              2 = level-2 cards (middle row), 
 *              3 = level-3 cards (bottom row))
 *    - index: position within that row (from left to right)
 *             Valid ranges:
 *                - level 1 -> indices 0 to 4
 *                - level 2 -> indices 0 to 3
 *                - level 3 -> indices 0 to 2
 *    - newCardData: data of the new card drawn from the top of the deck
 *                   (replacing the one you're booking on the card pyramid).
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the reservation is valid,
 *    - WINNING_MOVE if this move causes a win,
 *    - LOOSING_MOVE if the move is invalid (e.g., invalid level/index, exceeding max reserved cards).
 */
t_return_code bookCard(int level, int index, int* newCardData);  // index = position within the level (1,2 or 3). It should be between 0 & 4 if you choose level 1, 0 to 3 if you choose level 2, 0 to 2 if level 3.


/* -----------
 * Use this function to book a card blindly from the deck (instead of picking a visible one).
 * This move is used when you want to draw the top card from a level's deck
 * (which means you do not know the card beforehand).
 *
 * Like `*newCardData` in `bookCard()`, the card content is transfered to you from the server.
 *
 * Parameters:
 *    - level: the card level 
 *             (1 = level-1 card (top row), 
 *              2 = level-2 cards (middle row), 
 *              3 = level-3 cards (bottom row))
 *    - cardData: a pointer to an array of 12 integers representing the card
 *                (its full structure: token type, prestige, requirements, abilities (see jewel_card enum)).
 *                
 *
 * ⚠️⚠️
 *  TODO
 *   Note: this move grants a gold token automatically, unless you're already at token capacity (10).
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the move is valid,
 *    - WINNING_MOVE if the move causes a win,
 *    - LOOSING_MOVE if the move is invalid (e.g., too many booked cards).
 */
t_return_code bookBlindCard(int level, int* cardData);


/* -----------
 * Purchase a visible Jewel Card directly from the board.
 * You pay the full cost in tokens and/or permanent bonuses,
 * and the card is added to your collection (affecting your bonuses, prestige points, etc.).
 *
 * This move does not grant a gold token. It simply removes the selected card from the board
 * and adds another one (= newCardData) in the pyramid.
 * You should copy the data of the purchased card beforehand.
 *
 * Parameters:
 *    - level: the card level 
 *             (1 = level-1 card (top row), 
 *              2 = level-2 cards (middle row), 
 *              3 = level-3 cards (bottom row))
 *    - index: position within that row (from left to right)
 *             Valid ranges:
 *                - level 1 -> indices 0 to 4
 *                - level 2 -> indices 0 to 3
 *                - level 3 -> indices 0 to 2
 *    - newCardData: data of the new card drawn from the top of the deck
 *                   (replacing the one you're booking on the card pyramid).
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the purchase is valid,
 *    - WINNING_MOVE if the card leads to a win,
 *    - LOOSING_MOVE if the move is invalid (e.g., insufficient resources).
 */
t_return_code buyJewelCard(int level, int index, int* newCardData);


/* -----------
 * Purchase a previously reserved Jewel Card (i.e. one you booked earlier).
 * The card is removed from your reserved list and added to your collection,
 * affecting your bonuses, prestige points, and possibly triggering a crown bonus.
 *
 * No gold token is gained in this process as it is a pure payment and acquisition move,
 * just like `buyJewelCard()`.
 *
 * Parameters:
 *    - index: the index of the reserved card you want to buy (0-based)
 *             Valid range depends on how many cards you’ve booked 
 *             (max amount of booked cards is 3, therefore the max range is 0 to 2).
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the purchase is valid,
 *    - WINNING_MOVE if the card leads to a win,
 *    - LOOSING_MOVE if the move is invalid (e.g., not enough tokens or invalid index).
 */
t_return_code buyBookedCard(int index);  // index within the list of booked cards


/* -----------
 * Claim a Royal Card.
 * This move is triggered when you meet the crown requirements (= 3 or 6 crowns),
 * and lets you add a Royal Card to your collection. 
 * There are prestige points & often special abilities attached to them.
 *
 * You **must** call this function as soon as you're eligible to claim a royal.
 * Otherwise you'll lose the game.
 *
 * Parameters:
 *    - index: the index of the Royal Card you want to claim (0-based)
 *             Between 0 and 3. You shouldn't claim a Royal Card that was previously claimed.
 *
 * Returns a t_return_code:
 *    - NORMAL_MOVE if the card was claimed correctly,
 *    - WINNING_MOVE if claiming the card causes you to win,
 *    - LOOSING_MOVE if the move is invalid (e.g., claiming a card when you're not eligible or one that was previously claimed).
 */
t_return_code claimRoyalCard(int index); 


// TODO: change the rules: whenever somemone owns 10 tokens & buys a card to take or steal a token, we should ignore this ability.


/* ----------------------
 * Display the Game
 * in a pretty way (ask the server what to print)
 */
void printSplendorGame(int emoji);



/* ----------------------------
 * Send a comment to the server
 *
 * Parameters:
 * - comment: (string) comment to send to the server (max 100 char.)
 */
void sendComment(char* comment);



#endif
